import {
  Artifact,
  ArtifactType,
  ConlangLexeme,
  LocationData,
  Project,
  ProjectStatus,
  TaskData,
  TASK_STATE,
  CharacterData,
  WikiData,
  TimelineData,
  MemorySyncConversation,
  NpcMemoryRun,
} from './types';
import { createTamenzutMagicSystemData } from './utils/magicSystem';

export interface SeedWorkspace {
  projects: Project[];
  artifacts: Artifact[];
  xp: number;
  memoryConversations: MemorySyncConversation[];
  npcMemoryRuns: NpcMemoryRun[];
}

export const createSeedWorkspace = (ownerId: string): SeedWorkspace => {
  const projects: Project[] = [
    { id: 'proj-1', ownerId, title: 'Tamenzut', summary: 'A series of high-fantasy novels.', status: ProjectStatus.Active, tags: ['novel', 'fantasy'] },
    { id: 'proj-2', ownerId, title: 'Steamweave', summary: 'A coal-punk world of gears and magic.', status: ProjectStatus.Idea, tags: ['coal-punk', 'rpg'] },
    { id: 'proj-3', ownerId, title: 'Sacred Truth', summary: 'A supernatural investigation saga.', status: ProjectStatus.Active, tags: ['vampires', 'mystery'] },
    { id: 'proj-4', ownerId, title: 'Dustland', summary: 'A retro CRT RPG framework.', status: ProjectStatus.Active, tags: ['rpg', 'crt-aesthetic'] },
    { id: 'proj-5', ownerId, title: 'Aputi', summary: 'A timeline of the Aputi people.', status: ProjectStatus.Idea, tags: ['timeline', 'history'] },
  ];

  const artifacts: Artifact[] = [
    {
      id: 'art-1',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Conlang,
      title: 'Darv',
      summary: 'The ancient language of the Darv people.',
      status: 'draft',
      tags: ['language'],
      relations: [],
      data: [
        { id: 'lex-1', lemma: 'brubber', pos: 'adj', gloss: 'strange; unusual', etymology: 'From Old Darv "brub", meaning "other".' },
      ] as ConlangLexeme[],
    },
    {
      id: 'art-2',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Kaelen',
      summary: 'A rogue threadweaver still paying for the Dawn Gate sacrifice.',
      status: 'in-progress',
      tags: ['protagonist', 'tamenzut'],
      relations: [
        { toId: 'art-1', kind: 'SPEAKS' },
        { toId: 'art-3b', kind: 'APPEARS_IN' },
        { toId: 'art-10', kind: 'PROTAGONIST' },
        { toId: 'art-14', kind: 'ALLY_OF' },
        { toId: 'art-16', kind: 'TRACKED_IN' },
      ],
      data: {
        bio: "Kaelen grew up on the streets of the Gilded City, threading illusions to survive. After surrendering his silver focus to seal the Dawn Gate he now works with Liora to keep Tamenzut's archive from unraveling.",
        traits: [
          { id: 't1', key: 'Age', value: '27' },
          { id: 't2', key: 'Drive', value: 'Protect the found family of threadweavers.' },
          { id: 't3', key: 'Burden', value: 'Haunted by the Dawn Gate sacrifice.' },
          { id: 't4', key: 'Signature Move', value: 'Threads spectral relic copies to bypass wards.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-17',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Liora Sunforged',
      summary: 'An archivist-mentor weaving Tamenzut canon with Dustland tech.',
      status: 'draft',
      tags: ['mentor', 'tamenzut'],
      relations: [
        { toId: 'art-3b', kind: 'APPEARS_IN' },
        { toId: 'art-10', kind: 'MENTORS' },
        { toId: 'art-16', kind: 'TRACKED_IN' },
        { toId: 'art-30', kind: 'CHILD_OF' },
        { toId: 'art-31', kind: 'CHILD_OF' },
        { toId: 'art-32', kind: 'SIBLING_OF' },
        { toId: 'art-33', kind: 'PARTNER_OF' },
        { toId: 'art-34', kind: 'PARENT_OF' },
      ],
      data: {
        bio: "Liora helmed the Tamenzut archive before the cataclysm, cataloguing relics that bleed between worlds. She now trains Kaelen to balance sacred oaths with the experimental Dustland tech powering new thread looms.",
        traits: [
          { id: 'li-trait-1', key: 'Role', value: 'Archivist mentor of the Threads of Dawn cell.' },
          { id: 'li-trait-2', key: 'Conflict', value: 'Integrates Dustland tech into holy threadweaving rites.' },
          { id: 'li-trait-3', key: 'Promise', value: 'Will not let another protege pay the Dawn Gate price.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-30',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Aveline Sunforged',
      summary: 'Matriarch of the Sunforged archive line, keeper of ancestral vows.',
      status: 'complete',
      tags: ['family', 'mentor'],
      relations: [
        { toId: 'art-17', kind: 'PARENT_OF' },
        { toId: 'art-32', kind: 'PARENT_OF' },
        { toId: 'art-31', kind: 'PARTNER_OF' },
      ],
      data: {
        bio: 'Aveline curates the Sunforged bloodline ledger and maintains the threadlooms that chronicle their oaths.',
        traits: [
          { id: 'av-trait-1', key: 'Age', value: '63' },
          { id: 'av-trait-2', key: 'Focus', value: 'Preserving the archive line without repeating past sacrifices.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-31',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Thane Sunforged',
      summary: 'Field tactician who bridges Sunforged diplomacy with Dustland enclaves.',
      status: 'draft',
      tags: ['family', 'tamenzut'],
      relations: [
        { toId: 'art-17', kind: 'PARENT_OF' },
        { toId: 'art-32', kind: 'PARENT_OF' },
        { toId: 'art-30', kind: 'PARTNER_OF' },
      ],
      data: {
        bio: 'Thane commands the diplomatic wing of the archive, negotiating with Dustland enclaves for safe passage.',
        traits: [
          { id: 'th-trait-1', key: 'Age', value: '65' },
          { id: 'th-trait-2', key: 'Specialty', value: 'Tactical threadweaving and negotiation.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-32',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Joran Sunforged',
      summary: 'Liora\'s sibling, a wanderer cataloguing off-world anomalies.',
      status: 'in-progress',
      tags: ['family', 'explorer'],
      relations: [
        { toId: 'art-30', kind: 'CHILD_OF' },
        { toId: 'art-31', kind: 'CHILD_OF' },
        { toId: 'art-17', kind: 'SIBLING_OF' },
      ],
      data: {
        bio: 'Joran travels between breach sites to survey how the Dustland technology warps canon relics.',
        traits: [
          { id: 'jo-trait-1', key: 'Age', value: '29' },
          { id: 'jo-trait-2', key: 'Role', value: 'Archive scout and anomaly cartographer.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-33',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Maris Emberline',
      summary: 'Dustland technologist whose resonance arrays stabilize the archive.',
      status: 'in-progress',
      tags: ['partner', 'dustland'],
      relations: [
        { toId: 'art-17', kind: 'PARTNER_OF' },
        { toId: 'art-34', kind: 'PARENT_OF' },
      ],
      data: {
        bio: 'Maris reverse-engineers Dustland resonators to harmonize with Tamenzut lore vaults.',
        traits: [
          { id: 'ma-trait-1', key: 'Age', value: '31' },
          { id: 'ma-trait-2', key: 'Expertise', value: 'Hybridizing Dustland resonators with archive wards.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-34',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Character,
      title: 'Tamsin Sunforged',
      summary: 'Next-generation threadweaver balancing two traditions.',
      status: 'idea',
      tags: ['family', 'next-gen'],
      relations: [
        { toId: 'art-17', kind: 'CHILD_OF' },
        { toId: 'art-33', kind: 'CHILD_OF' },
      ],
      data: {
        bio: 'Tamsin experiments with weaving Dustland signal code directly into Tamenzut vows to keep both legacies alive.',
        traits: [
          { id: 'ta-trait-1', key: 'Age', value: '7' },
          { id: 'ta-trait-2', key: 'Dream', value: 'Bridge the archive and Dustland schools without loss.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-3',
      ownerId,
      projectId: 'proj-2',
      type: ArtifactType.ShortStory,
      title: 'Shroud and Gears',
      summary: 'An introductory short story.',
      status: 'idea',
      tags: ['short-story'],
      relations: [],
      data: [],
    },
    {
      id: 'art-3b',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Novel,
      title: 'Tamenzut: Threads of Dawn',
      summary: "Series outline mapping Kaelen and Liora's first arc.",
      status: 'draft',
      tags: ['novel', 'outline'],
      relations: [
        { toId: 'art-2', kind: 'FEATURES' },
        { toId: 'art-17', kind: 'FEATURES' },
        { toId: 'art-16', kind: 'STRUCTURES' },
      ],
      data: [],
    },
    {
      id: 'art-4',
      ownerId,
      projectId: 'proj-2',
      type: ArtifactType.Task,
      title: 'Design main character',
      summary: 'Flesh out the protagonist for Shroud and Gears.',
      status: 'in-progress',
      tags: ['design'],
      relations: [],
      data: { state: TASK_STATE.InProgress } as TaskData,
    },
    {
      id: 'art-5',
      ownerId,
      projectId: 'proj-2',
      type: ArtifactType.Task,
      title: 'Outline Chapter 1',
      summary: 'Create beat sheet for the first chapter.',
      status: 'todo',
      tags: ['writing'],
      relations: [],
      data: { state: TASK_STATE.Todo } as TaskData,
    },
    {
      id: 'art-6',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Wiki,
      title: 'World Anvil',
      summary: 'Main wiki for the Tamenzut universe.',
      status: 'draft',
      tags: ['world-building'],
      relations: [],
      data: { content: '# Welcome to Tamenzut' } as WikiData,
    },
    {
      id: 'art-7',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Location,
      title: 'The Gilded City',
      summary: 'A bustling desert metropolis.',
      status: 'draft',
      tags: ['city'],
      relations: [],
      data: {
        description: 'A city built on an oasis, known for its vibrant trade and towering spires of sandstone and gold.',
        features: [{ id: 'f1', name: 'The Sunstone Market', description: 'A sprawling bazaar.' }],
      } as LocationData,
    },
    {
      id: 'art-8',
      ownerId,
      projectId: 'proj-5',
      type: ArtifactType.Timeline,
      title: 'Aputi People Timeline',
      summary: 'A historical timeline of the Aputi people.',
      status: 'draft',
      tags: ['history', 'timeline'],
      relations: [],
      data: {
        events: [
          { id: 'ev-1', date: '-1000', title: 'First Settlers', description: 'The first Aputi settlers arrive in the valley.' },
          { id: 'ev-2', date: '-500', title: 'The Great Flood', description: 'A great flood reshapes the landscape.' },
          { id: 'ev-3', date: '-120', title: 'Treaty of Three Peaks', description: 'The valley tribes unite under a shared lunar charter.' },
          { id: 'ev-4', date: '85', title: 'Resonance Accord', description: 'Crystal harmonics unlock long-distance memory sharing.' },
          { id: 'ev-5', date: '340', title: 'Sky Harbor Completed', description: 'A floating port cements Aputi dominance of the trade winds.' },
        ],
      } as TimelineData,
    },
    {
      id: 'art-9',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Terminology,
      title: 'Glossary of Darv Terms',
      summary: 'A list of common terms in the Darv language.',
      status: 'draft',
      tags: ['glossary', 'darv'],
      relations: [{ toId: 'art-1', kind: 'DEFINES' }],
      data: [],
    },
    {
      id: 'art-10',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Chapter,
      title: 'Chapter 1: The Sunstone Market',
      summary: 'Opening chapter where Kaelen meets Liora amidst the Sunstone Market sting.',
      status: 'draft',
      tags: ['writing', 'chapter'],
      relations: [
        { toId: 'art-7', kind: 'SET_IN' },
        { toId: 'art-2', kind: 'STARS' },
        { toId: 'art-17', kind: 'MENTORS' },
        { toId: 'art-16', kind: 'BEAT_OF' },
      ],
      data: [],
    },
    {
      id: 'art-16',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Timeline,
      title: 'Threads of Dawn Arc Beats',
      summary: 'Milestones that evolve Kaelen and Liora across the first novel.',
      status: 'draft',
      tags: ['timeline', 'arc'],
      relations: [
        { toId: 'art-2', kind: 'TRACKS' },
        { toId: 'art-17', kind: 'TRACKS' },
        { toId: 'art-3b', kind: 'INFORMS' },
        { toId: 'art-10', kind: 'INCLUDES' },
      ],
      data: {
        events: [
          {
            id: 'tam-ev-1',
            date: '1.1207',
            title: 'Dawn Gate sacrifice',
            description: 'Kaelen relinquishes his silver focus to seal the portal and fractures the guild hierarchy.',
          },
          {
            id: 'tam-ev-2',
            date: '1.1210',
            title: 'Liora recruits Kaelen',
            description: 'Liora reveals the archive breach and binds Kaelen to the Threads of Dawn taskforce.',
          },
          {
            id: 'tam-ev-3',
            date: '1.1212',
            title: 'Archive covenant',
            description: 'Together they fuse Dustland tech with Tamenzut wards, redefining the rules of threadweaving.',
          },
        ],
      } as TimelineData,
    },
    {
      id: 'art-11',
      ownerId,
      projectId: 'proj-4',
      type: ArtifactType.GameModule,
      title: 'The Sunken City',
      summary: 'An adventure module for the Dustland RPG.',
      status: 'idea',
      tags: ['module', 'adventure'],
      relations: [],
      data: [],
    },
    {
      id: 'art-18',
      ownerId,
      projectId: 'proj-4',
      type: ArtifactType.Character,
      title: 'Rustwatch Captain Sel',
      summary: 'Leads the Rustwatch patrol keeping the Dustland hub secure.',
      status: 'draft',
      tags: ['npc', 'dustland'],
      relations: [
        { toId: 'art-11', kind: 'PATROLS' },
      ],
      data: {
        bio: 'Sel orchestrates overlapping patrol routes and decides when to escalate incursions near the players\' hub.',
        traits: [
          { id: 'sel-trait-1', key: 'Role', value: 'Rustwatch captain' },
          { id: 'sel-trait-2', key: 'Tension', value: 'Balancing hub safety with player freedom.' },
        ],
      } as CharacterData,
    },
    {
      id: 'art-12',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.MagicSystem,
      title: 'Threadweaving Codex',
      summary: 'Structure, rituals, and taboos of Tamenzut threadweaving.',
      status: 'draft',
      tags: ['magic', 'tamenzut'],
      relations: [],
      data: createTamenzutMagicSystemData(),
    },
    {
      id: 'art-13',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Timeline,
      title: 'Threadweaving History',
      summary: 'Pivotal events that shaped Tamenzut magic.',
      status: 'draft',
      tags: ['timeline', 'tamenzut'],
      relations: [
        { toId: 'art-12', kind: 'DOCUMENTS' },
        { toId: 'art-14', kind: 'MONITORED_BY' },
      ],
      data: {
        events: [
          { id: 'tw-1', date: '-430', title: 'Discovery of the Solar Looms', description: 'Miners uncover the first loom tower beneath the Gilded City.' },
          { id: 'tw-2', date: '-75', title: 'Continuity Wardens Charter', description: 'The wardens formalize the cost-ledger that governs weaves.' },
          { id: 'tw-3', date: '112', title: 'Edruel Accord', description: 'Ancestral archivists teach restoration rites to prevent loom collapse.' },
          { id: 'tw-4', date: '265', title: 'Veil Fracture at Dawnspire', description: 'A rogue syndicate tears the veil, forcing the Wardens to intervene.' },
        ],
      } as TimelineData,
    },
    {
      id: 'art-14',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Faction,
      title: 'Continuity Wardens',
      summary: 'Archivist-sentinels who balance every weave with a sworn cost.',
      status: 'draft',
      tags: ['faction', 'tamenzut'],
      relations: [
        { toId: 'art-2', kind: 'ENLISTS' },
        { toId: 'art-7', kind: 'OPERATES_FROM' },
        { toId: 'art-12', kind: 'REGULATES' },
        { toId: 'art-15', kind: 'OPPOSES' },
        { toId: 'art-13', kind: 'ARCHIVES' },
      ],
      data: {},
    },
    {
      id: 'art-15',
      ownerId,
      projectId: 'proj-1',
      type: ArtifactType.Faction,
      title: 'Solar Loom Syndicate',
      summary: 'A clandestine guild siphoning loom energy for profit.',
      status: 'in-progress',
      tags: ['faction', 'antagonist'],
      relations: [
        { toId: 'art-7', kind: 'INFILTRATES' },
        { toId: 'art-12', kind: 'ABUSES' },
        { toId: 'art-2', kind: 'HUNTS' },
      ],
      data: {},
    },
  ];

  const memoryConversations: MemorySyncConversation[] = [
    {
      id: 'mem-conv-1',
      projectId: 'proj-1',
      title: 'Gemini sync — Kaelen and the Dawn Gate incident',
      summary:
        'Gemini flagged pivotal beats from the latest Tamenzut session and suggested which artifacts should absorb the memories.',
      scope: 'global',
      updatedAt: '2024-07-12T15:30:00Z',
      transcript: [
        {
          id: 'mem-conv-1-msg-1',
          role: 'creator',
          text: 'Capture the moment Kaelen gives up the silver focus to seal the Dawn Gate. It needs to persist across chapters.',
          timestamp: '2024-07-12T15:24:00Z',
        },
        {
          id: 'mem-conv-1-msg-2',
          role: 'gemini',
          text: 'Logged. Recommending we update Kaelen\'s character sheet and the Darv glossary with the new ritual keyword.',
          timestamp: '2024-07-12T15:24:40Z',
        },
        {
          id: 'mem-conv-1-msg-3',
          role: 'creator',
          text: 'Only sync it if I approve—this is now canon-sensitive.',
          timestamp: '2024-07-12T15:25:05Z',
        },
      ],
      suggestions: [
        {
          id: 'mem-sug-1',
          statement: 'Add a “Dawn Gate sacrifice” memory beat to Kaelen\'s profile.',
          rationale: 'Ensures Kaelen\'s future decisions recall the cost of closing the portal.',
          status: 'pending',
          createdAt: '2024-07-12T15:30:00Z',
          artifactId: 'art-2',
          artifactTitle: 'Kaelen',
          tags: ['character', 'memory'],
          canonicalSensitivity: 'high',
        },
        {
          id: 'mem-sug-2',
          statement: 'Append the ritual keyword “solenne” to the Darv glossary entry.',
          rationale: 'Gemini inferred that the chant becomes a recurring trigger for the leyline wards.',
          status: 'approved',
          createdAt: '2024-07-12T15:30:00Z',
          updatedAt: '2024-07-12T15:34:12Z',
          artifactId: 'art-9',
          artifactTitle: 'Glossary of Darv Terms',
          tags: ['language', 'ritual'],
          canonicalSensitivity: 'moderate',
        },
      ],
      lastSyncedAt: '2024-07-12T15:34:12Z',
    },
    {
      id: 'mem-conv-2',
      projectId: 'proj-4',
      title: 'Dustland — NPC patrol routes refresh',
      summary:
        'Gemini highlighted patrol data for Dustland NPCs so the retro CRT encounter tables stay aligned with the latest playtest.',
      scope: 'npc',
      updatedAt: '2024-06-18T19:12:00Z',
      transcript: [
        {
          id: 'mem-conv-2-msg-1',
          role: 'gemini',
          text: 'Detected new chatter about the Rustwatch patrol overlapping with the player hub. Offer to sync?',
          timestamp: '2024-06-18T19:09:12Z',
        },
        {
          id: 'mem-conv-2-msg-2',
          role: 'creator',
          text: 'Log it, but I want to review before it touches the module.',
          timestamp: '2024-06-18T19:10:01Z',
        },
      ],
      suggestions: [
        {
          id: 'mem-sug-3',
          statement: 'Update “The Sunken City” module with Rustwatch patrol overlap notes.',
          rationale: 'Keeps encounter pacing consistent when players camp near the hub.',
          status: 'pending',
          createdAt: '2024-06-18T19:12:00Z',
          artifactId: 'art-11',
          artifactTitle: 'The Sunken City',
          tags: ['module', 'encounter'],
          canonicalSensitivity: 'moderate',
        },
      ],
    },
  ];

  const npcMemoryRuns: NpcMemoryRun[] = [
    {
      id: 'npc-run-1',
      projectId: 'proj-1',
      npcArtifactId: 'art-2',
      npcName: 'Kaelen',
      npcType: ArtifactType.Character,
      scope: 'npc',
      pendingSuggestions: 1,
      approvedSuggestions: 1,
      highestCanonicalSensitivity: 'high',
      lastRunAt: '2024-07-12T15:30:00Z',
      lastApprovedAt: '2024-07-12T15:34:12Z',
    },
    {
      id: 'npc-run-2',
      projectId: 'proj-4',
      npcArtifactId: 'art-18',
      npcName: 'Rustwatch Captain Sel',
      npcType: ArtifactType.Character,
      scope: 'npc',
      pendingSuggestions: 1,
      approvedSuggestions: 0,
      highestCanonicalSensitivity: 'moderate',
      lastRunAt: '2024-06-18T19:12:00Z',
    },
  ];

  return {
    projects,
    artifacts,
    xp: 25,
    memoryConversations,
    npcMemoryRuns,
  };
};

