runtime: nodejs20
env: standard

entrypoint: npm start

env_variables:
  NODE_ENV: production
  ALLOWED_ORIGINS: https://creative-atlas.web.app
  GITHUB_CLIENT_ID: "placeholder"
  GITHUB_CLIENT_SECRET: "placeholder"
  APP_BASE_URL: "placeholder"
