runtime: nodejs20
env: standard

entrypoint: npm start

env_variables:
  NODE_ENV: production
  ALLOWED_ORIGINS: https://creative-atlas.web.app
  CA_GITHUB_CLIENT_ID: "placeholder"
  CA_GITHUB_CLIENT_SECRET: "placeholder"
  APP_BASE_URL: "placeholder"
  SESSION_SECRET: "replace_me"
  GEMINI_API_KEY: "placeholder"
  ENABLE_GCP_LOGGING: "true"
  OPERATIONS_LOG_NAME: "creative-atlas-operations"
  REQUEST_WARNING_THRESHOLD_MS: "4000"
